// RFC 2822 Header Enums
import "./AddressRole.tsp";
import "./HeaderFieldCategory.tsp";
import "./HeaderFieldValueType.tsp";
import "./HeaderFieldName.tsp";
import "./ReferenceType.tsp";

// IMAP Enums
import "./MessageFlag.tsp";
import "./ConnectionState.tsp";
import "./NamespaceType.tsp";
import "./MailboxAttribute.tsp";
import "./MailboxSpecialUse.tsp";

// MIME Enums
import "./MediaType.tsp";
import "./TransferEncoding.tsp";
import "./ContentDisposition.tsp";
import "./MultipartSubtype.tsp";

// Storage Enums
import "./StorageType.tsp";
import "./ContentEncoding.tsp";
