// RFC 2822 Header Enums
import "./AddressRole.tsp";
import "./ReferenceType.tsp";

// IMAP Enums
import "./MessageFlag.tsp";
import "./ConnectionState.tsp";
import "./NamespaceType.tsp";
import "./MailboxAttribute.tsp";
import "./MailboxSpecialUse.tsp";
import "./MailboxSyncStatus.tsp";

// MIME Enums
import "./MediaType.tsp";
import "./TransferEncoding.tsp";
import "./ContentDisposition.tsp";
import "./MultipartSubtype.tsp";

// Storage Enums
import "./StorageType.tsp";
import "./ContentEncoding.tsp";

// Thread Enums
import "./StarColor.tsp";

// Message Status Enums
import "./MessageStatus.tsp";
import "./MessageSyncStatus.tsp";
import "./OutboxMessageStatus.tsp";
import "./MessageCategory.tsp";
import "./SenderTrust.tsp";

// Account Enums
import "./AccountConfigState.tsp";

// API Enums
import "./SortOrder.tsp";
