@maxLength(25)
@minLength(25)
scalar UUID extends string;

@maxLength(2048)
scalar String2048 extends string;

@maxLength(800)
scalar String800 extends string;

@maxLength(512)
scalar String512 extends string;

@maxLength(256)
scalar String256 extends string;

@maxLength(200)
scalar String200 extends string;

@maxLength(140)
scalar String140 extends string;

@maxLength(64)
scalar String64 extends string;

@maxLength(32)
scalar String32 extends string;
