/**
 * The one path the edge lets through unauthenticated.
 *
 * Microsoft redirects the browser here after consent, so the request arrives
 * with no Authorization header and nothing to mint one from; gating it 401s the
 * OAuth flow before the proxy hop. The HMAC-signed `state` parameter the handler
 * validates is what protects the callback, not a token.
 *
 * Hardcoded, and deliberately not read out of the spec: an operation marked
 * `NoAuth` does not become public at the edge by saying so. A future public
 * route is added to this list by hand, with the same thought behind it.
 */
export const PUBLIC_ROUTES: readonly { method: string; path: string }[] = [
	{ method: "GET", path: "/accounts/oauth/microsoft/callback" },
];

export interface Route {
	id: string;
	uri: string;
	methods: readonly string[] | null;
	authenticated: boolean;
}

const toApisixUri = (openapiPath: string): string =>
	openapiPath.replace(/\{([^}]+)\}/g, ":$1");

const publicRoute = (path: string): { method: string } | undefined =>
	PUBLIC_ROUTES.find((route) => route.path === path);

export const buildRoutes = (paths: readonly string[]): Route[] =>
	paths.map((path, index) => {
		const exempt = publicRoute(path);
		return {
			id: `route-${index}`,
			uri: toApisixUri(path),
			// The exemption covers one method. Anything else sent to the path
			// matches no route and stops at the edge.
			methods: exempt ? [exempt.method] : null,
			authenticated: exempt === undefined,
		};
	});

interface ConfigInput {
	routes: readonly Route[];
	oidcPlugin: string;
	backendHost: string;
	backendPort: number;
}

const yamlEscape = (value: string): string => value.replace(/'/g, "''");

const renderRoute = (route: Route, oidcPlugin: string): string => {
	const methods =
		route.methods === null
			? ""
			: `\n    methods:\n${route.methods.map((method) => `      - ${method}`).join("\n")}`;
	const plugins = route.authenticated ? `\n    plugins:\n${oidcPlugin}` : "";
	return `  - id: ${route.id}
    uri: '${yamlEscape(route.uri)}'${methods}
    upstream_id: backend${plugins}`;
};

export const renderConfig = ({
	routes,
	oidcPlugin,
	backendHost,
	backendPort,
}: ConfigInput): string => `# GENERATED by packages/apisix/generate-config.ts — do not edit by hand.
# APISIX standalone (etcd-less) route table for the self-host edge tier.
routes:
  - id: auth-public
    uri: /api/auth/*
    upstream_id: backend
  - id: health
    uri: /health
    upstream_id: backend
${routes.map((route) => renderRoute(route, oidcPlugin)).join("\n")}
upstreams:
  - id: backend
    type: roundrobin
    nodes:
      '${backendHost}:${backendPort}': 1
#END
`;

/**
 * A public path the spec no longer declares would silently gate nothing, so the
 * generator refuses rather than writing a table whose exemption is dead.
 */
export const assertPublicRoutesExist = (paths: readonly string[]): void => {
	const declared = new Set(paths);
	for (const route of PUBLIC_ROUTES) {
		if (declared.has(route.path)) continue;
		throw new Error(
			`apisix: ${route.path} is exempted from edge authentication but the OpenAPI spec declares no such path`,
		);
	}
};
