/**
 * An APISIX `vars` expression: field, operator, operand.
 *
 * Written out rather than derived, because it narrows an exemption. A route
 * whose `uri` ends in a wildcard is matched by more requests than the OpenAPI
 * path it came from, and everything extra it matches is public — so a path that
 * routes as a wildcard states the shape it actually meant.
 */
export type RouteCondition = readonly [string, string, string];

// base64url over the 32 random bytes a feed token is minted from, which is 43
// characters — the shape @remit/calendar-service mints and checks. The suffix is
// a literal here, unlike in the router, so `<token>Xics` is not public either.
const CALENDAR_FEED_URI_PATTERN = "^/feeds/calendar/[A-Za-z0-9_-]{43}\\.ics$";

/**
 * The paths the edge lets through unauthenticated.
 *
 * Microsoft redirects the browser here after consent, so the request arrives
 * with no Authorization header and nothing to mint one from; gating it 401s the
 * OAuth flow before the proxy hop. The HMAC-signed `state` parameter the handler
 * validates is what protects the callback, not a token.
 *
 * A calendar feed is the same shape of problem: Apple Calendar, Google Calendar
 * and Thunderbird poll a URL and send no credential, so the token in the path is
 * the credential and a bearer gate here would refuse every subscriber.
 *
 * Hardcoded, and deliberately not read out of the spec: an operation marked
 * `NoAuth` does not become public at the edge by saying so. A future public
 * route is added to this list by hand, with the same thought behind it.
 */
export const PUBLIC_ROUTES: readonly {
	method: string;
	path: string;
	vars?: readonly RouteCondition[];
}[] = [
	{ method: "GET", path: "/accounts/oauth/microsoft/callback" },
	{
		method: "GET",
		path: "/feeds/calendar/{feedToken}.ics",
		vars: [["uri", "~~", CALENDAR_FEED_URI_PATTERN]],
	},
];

export interface Route {
	id: string;
	uri: string;
	methods: readonly string[] | null;
	vars: readonly RouteCondition[] | null;
	authenticated: boolean;
}

/**
 * The APISIX form of an OpenAPI path.
 *
 * A segment that is exactly one parameter becomes `:name`. A segment that mixes
 * a parameter with literal text — `{feedToken}.ics` — has no `:name` spelling
 * radixtree can express, so the route ends in the `*` wildcard instead. That
 * only holds on the last segment, and a spec that puts such a segment anywhere
 * else fails the generator rather than being written out as a route that
 * silently matches the wrong requests.
 */
const toApisixUri = (openapiPath: string): string => {
	const segments = openapiPath.split("/");
	const mixed = segments.findIndex(
		(segment) => /\{[^}]+\}/.test(segment) && !/^\{[^}]+\}$/.test(segment),
	);
	if (mixed === -1) {
		return openapiPath.replace(/\{([^}]+)\}/g, ":$1");
	}
	if (mixed !== segments.length - 1) {
		throw new Error(
			`apisix: ${openapiPath} mixes a path parameter with literal text outside its last segment, which has no route form`,
		);
	}
	return [...segments.slice(0, mixed), "*"]
		.join("/")
		.replace(/\{([^}]+)\}/g, ":$1");
};

const publicRoute = (path: string) =>
	PUBLIC_ROUTES.find((route) => route.path === path);

export const buildRoutes = (paths: readonly string[]): Route[] =>
	paths.map((path, index) => {
		const exempt = publicRoute(path);
		return {
			id: `route-${index}`,
			uri: toApisixUri(path),
			// The exemption covers one method. Anything else sent to the path
			// matches no route and stops at the edge.
			methods: exempt ? [exempt.method] : null,
			vars: exempt?.vars ?? null,
			authenticated: exempt === undefined,
		};
	});

interface ConfigInput {
	routes: readonly Route[];
	oidcPlugin: string;
	backendHost: string;
	backendPort: number;
}

const yamlEscape = (value: string): string => value.replace(/'/g, "''");

const renderRoute = (route: Route, oidcPlugin: string): string => {
	const methods =
		route.methods === null
			? ""
			: `\n    methods:\n${route.methods.map((method) => `      - ${method}`).join("\n")}`;
	// JSON flow scalars, so a pattern full of backslashes and brackets needs no
	// YAML quoting decision taken by hand.
	const vars =
		route.vars === null
			? ""
			: `\n    vars:\n${route.vars.map((condition) => `      - ${JSON.stringify(condition)}`).join("\n")}`;
	const plugins = route.authenticated ? `\n    plugins:\n${oidcPlugin}` : "";
	return `  - id: ${route.id}
    uri: '${yamlEscape(route.uri)}'${methods}${vars}
    upstream_id: backend${plugins}`;
};

export const renderConfig = ({
	routes,
	oidcPlugin,
	backendHost,
	backendPort,
}: ConfigInput): string => `# GENERATED by packages/apisix/generate-config.ts — do not edit by hand.
# APISIX standalone (etcd-less) route table for the self-host edge tier.
routes:
  - id: auth-public
    uri: /api/auth/*
    upstream_id: backend
  - id: health
    uri: /health
    upstream_id: backend
${routes.map((route) => renderRoute(route, oidcPlugin)).join("\n")}
upstreams:
  - id: backend
    type: roundrobin
    nodes:
      '${backendHost}:${backendPort}': 1
#END
`;

/**
 * A public path the spec no longer declares would silently gate nothing, so the
 * generator refuses rather than writing a table whose exemption is dead.
 */
export const assertPublicRoutesExist = (paths: readonly string[]): void => {
	const declared = new Set(paths);
	for (const route of PUBLIC_ROUTES) {
		if (declared.has(route.path)) continue;
		throw new Error(
			`apisix: ${route.path} is exempted from edge authentication but the OpenAPI spec declares no such path`,
		);
	}
};
