import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import { fileURLToPath } from "node:url";

const workerPath = fileURLToPath(
	new URL("../../public/mockServiceWorker.js", import.meta.url),
);
const mswPackagePath = fileURLToPath(
	new URL("../../../../node_modules/msw/package.json", import.meta.url),
);

describe("mockServiceWorker.js", () => {
	it("matches the installed msw version", () => {
		const workerSource = readFileSync(workerPath, "utf8");
		const versionMatch = workerSource.match(
			/PACKAGE_VERSION\s*=\s*['"]([^'"]+)['"]/,
		);
		assert.ok(
			versionMatch,
			"expected mockServiceWorker.js to declare PACKAGE_VERSION",
		);

		const installedVersion = JSON.parse(
			readFileSync(mswPackagePath, "utf8"),
		).version;

		assert.equal(
			versionMatch[1],
			installedVersion,
			`mockServiceWorker.js was generated by msw ${versionMatch[1]}, but msw ${installedVersion} is installed — regenerate it with "npm run msw:init"`,
		);
	});
});
