#!/usr/bin/env node
// Emits tmp/parity/report.md — one row per state × viewport × theme,
// grouped by surface with section headers and a top summary line.
//
// Run via: npm run parity:report -w packages/remit-web-client

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { manifest } from "./parity.manifest.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const THEMES = ["light", "dark"] as const;
type Theme = (typeof THEMES)[number];

type ReportRow = {
	surface: string;
	state: string;
	viewport: string;
	theme: Theme;
	needsStory: boolean;
};

function buildRows(): ReportRow[] {
	const rows: ReportRow[] = [];
	for (const entry of manifest) {
		for (const viewport of entry.viewports) {
			for (const theme of THEMES) {
				rows.push({
					surface: entry.surface,
					state: entry.state,
					viewport,
					theme,
					needsStory: entry.story === null,
				});
			}
		}
	}
	return rows;
}

function mdRow(
	surface: string,
	state: string,
	viewport: string,
	theme: Theme,
	needsStory: boolean,
): string {
	const storyFlag = needsStory ? "needs a story" : "";
	return `| ${surface} | ${state} | ${viewport} | ${theme} | ${storyFlag} |  |  |`;
}

function render(rows: ReportRow[]): string {
	const totalCells = rows.length;
	const needsStoryCount = rows.filter((r) => r.needsStory).length;

	const surfaces = [...new Set(rows.map((r) => r.surface))];

	const lines: string[] = [
		`<!-- Generated by parity:report — do not edit by hand -->`,
		``,
		`**Summary:** ${totalCells} cells total · ${needsStoryCount} flagged "needs a story" (story:null in manifest)`,
		``,
		`| surface | state | viewport | theme | issue | severity | correct-side |`,
		`| ------- | ----- | -------- | ----- | ----- | -------- | ------------ |`,
	];

	for (const surface of surfaces) {
		const surfaceRows = rows.filter((r) => r.surface === surface);

		lines.push(`| **${surface}** | | | | | | |`);
		for (const row of surfaceRows) {
			lines.push(
				mdRow(row.surface, row.state, row.viewport, row.theme, row.needsStory),
			);
		}
	}

	return lines.join("\n") + "\n";
}

function main(): void {
	const rows = buildRows();
	const md = render(rows);

	const outPath = resolve(__dirname, "../../../../tmp/parity/report.md");
	mkdirSync(dirname(outPath), { recursive: true });
	writeFileSync(outPath, md, "utf8");

	const totalCells = rows.length;
	const needsStoryCount = rows.filter((r) => r.needsStory).length;
	console.log(
		`report.md written → ${outPath} (${totalCells} cells, ${needsStoryCount} need a story)`,
	);
}

main();
