#!/usr/bin/env node --import tsx
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { shouldVerifyDiscoveryTls } from "@remit/auth-service/edge-tls";

/**
 * Generate the APISIX standalone (etcd-less) route table from the OpenAPI spec.
 *
 * Every business route is guarded by the openid-connect plugin in bearer_only
 * mode, which verifies the better-auth RS256 JWT against the JWKS it discovers
 * and follows key rotation automatically. better-auth's own endpoints
 * (`/api/auth/*`) stay public — that is where tokens are minted and the JWKS is
 * served. The backend re-verifies the JWT and derives identity itself, so the
 * edge only needs to gate — it forwards no identity header.
 */

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");

const BACKEND_HOST = process.env.APISIX_BACKEND_HOST ?? "host.docker.internal";
const BACKEND_PORT = Number(process.env.APISIX_BACKEND_PORT ?? "5436");
const DISCOVERY_URL =
	process.env.APISIX_OIDC_DISCOVERY ??
	`http://${BACKEND_HOST}:${BACKEND_PORT}/api/auth/.well-known/openid-configuration`;

interface OpenApiSpec {
	paths: Record<string, unknown>;
}

const toApisixUri = (openapiPath: string): string =>
	openapiPath.replace(/\{([^}]+)\}/g, ":$1");

const yamlEscape = (value: string): string => value.replace(/'/g, "''");

const spec: OpenApiSpec = JSON.parse(
	readFileSync(
		resolve(REPO_ROOT, "build/remit-openapi3/openapi.json"),
		"utf-8",
	),
);

const sslVerify = shouldVerifyDiscoveryTls(DISCOVERY_URL);

const oidcPlugin = `      openid-connect:
        bearer_only: true
        use_jwks: true
        ssl_verify: ${sslVerify}
        discovery: '${yamlEscape(DISCOVERY_URL)}'
        client_id: remit-web
        client_secret: unused-in-bearer-only
        set_userinfo_header: false
        set_id_token_header: false`;

const businessRoutes = Object.keys(spec.paths)
	.map((path, index) => {
		const uri = toApisixUri(path);
		return `  - id: route-${index}
    uri: '${yamlEscape(uri)}'
    upstream_id: backend
    plugins:
${oidcPlugin}`;
	})
	.join("\n");

const config = `# GENERATED by apisix/generate-config.ts — do not edit by hand.
# APISIX standalone (etcd-less) route table for the Postgres-parity edge tier.
routes:
  - id: auth-public
    uri: /api/auth/*
    upstream_id: backend
  - id: health
    uri: /health
    upstream_id: backend
${businessRoutes}
upstreams:
  - id: backend
    type: roundrobin
    nodes:
      '${BACKEND_HOST}:${BACKEND_PORT}': 1
#END
`;

const outPath = resolve(__dirname, "apisix.yaml");
writeFileSync(outPath, config);
console.log(
	`apisix: wrote ${Object.keys(spec.paths).length} business routes → ${outPath}`,
);
