import type { StorybookConfig } from "@storybook/react-vite";

const config: StorybookConfig = {
	// Glob remit-ui's co-located stories plus the workbench flow stories.
	stories: [
		"../../remit-ui/src/**/*.stories.@(ts|tsx)",
		"../src/**/*.stories.@(ts|tsx)",
	],
	addons: [],
	framework: {
		name: "@storybook/react-vite",
		options: {},
	},
	// Serves the MSW service worker generated by `npm run msw:init`.
	staticDirs: ["../public"],
	core: { disableTelemetry: true },
	async viteFinal(config) {
		const { default: tailwindcss } = await import("@tailwindcss/vite");
		config.plugins = config.plugins ?? [];
		config.plugins.push(tailwindcss());
		return config;
	},
};

export default config;
