import type { StorybookConfig } from "@storybook/react-vite";

const config: StorybookConfig = {
	// Glob remit-ui's co-located stories, the web-client's co-located stories
	// (leaf presentational components with no shell/router dependency), and
	// the workbench flow stories.
	stories: [
		"../../ui/src/**/*.stories.@(ts|tsx)",
		"../../web-client/src/**/*.stories.@(ts|tsx)",
		"../src/**/*.stories.@(ts|tsx)",
	],
	addons: [],
	framework: {
		name: "@storybook/react-vite",
		options: {},
	},
	// Serves the MSW service worker generated by `npm run msw:init`.
	staticDirs: ["../public"],
	core: { disableTelemetry: true },
	async viteFinal(config) {
		const { default: tailwindcss } = await import("@tailwindcss/vite");
		const { fileURLToPath, URL } = await import("node:url");
		config.plugins = config.plugins ?? [];
		config.plugins.push(tailwindcss());
		// In a git worktree the shared node_modules symlinks resolve @remit/*
		// packages back to the main checkout. Override here so Storybook picks
		// up the worktree's own source (needed for design-token / component changes).
		config.resolve = config.resolve ?? {};
		config.resolve.alias = {
			...(config.resolve.alias ?? {}),
			"@remit/ui/tokens.css": fileURLToPath(
				new URL("../../ui/src/tokens.css", import.meta.url),
			),
			"@remit/ui": fileURLToPath(
				new URL("../../ui/src/index.ts", import.meta.url),
			),
			// web-client stories (e.g. ConfirmDialog) use its own "@/" alias for
			// in-package imports — mirrors `webClientAlias()` in
			// packages/web-client/vite.base.ts, which Storybook doesn't load.
			"@": fileURLToPath(new URL("../../web-client/src", import.meta.url)),
		};
		return config;
	},
};

export default config;
