import {
	CONFIG_KIND,
	type ConfigAccount,
	type ConfigAddressFlags,
	type ConfigAddressFlagsEntry,
	type ConfigFilter,
	type ConfigLabel,
	CURRENT_SCHEMA_VERSION,
	type ReaderConfigDocument,
	ReaderConfigDocumentSchema,
} from "@remit/config-format";
import type {
	AccountItem,
	AddressFlags,
	AddressItem,
	FilterAnchorItem,
	FilterItem,
	LabelItem,
	MailboxItem,
} from "@remit/data-ports";
import { NotFoundError } from "@remit/data-ports/errors";
import { AccountAuthType } from "@remit/domain-enums";
import type {
	ConfigExportIdentity,
	ConfigExportRepositories,
} from "./repositories.js";
import {
	type AccountSettingsView,
	emptyAccountSettings,
	type MailboxSettingsView,
	readSettings,
	type SettingsView,
} from "./settings.js";

/**
 * The named sentinel a Filter carries for "no action of this kind". Filter
 * stores `"None"` rather than an absent field, so the export has to read the
 * sentinel rather than a nullish check.
 */
const NO_ACTION = "None";

/** Which credential the account needs before it can sync again. */
const credentialsFor = (account: AccountItem): ConfigAccount["credentials"] =>
	account.authType === AccountAuthType.OauthMicrosoft
		? { required: "oauth", provider: "microsoft" }
		: { required: "password" };

/**
 * Every mailbox in the configuration, by id, plus which account holds it.
 * Folder-referencing config is stored against mailbox ids, and every one of
 * them is regenerated by the next discovery — resolving each to its IMAP path
 * here is what makes the file mean anything on the other side.
 */
interface MailboxIndex {
	pathOf: (mailboxId: string) => string | undefined;
	accountOf: (mailboxId: string) => string | undefined;
	pathsOfAccount: (accountId: string) => Map<string, string>;
}

const buildMailboxIndex = (
	byAccount: ReadonlyMap<string, MailboxItem[]>,
): MailboxIndex => {
	const paths = new Map<string, string>();
	const owners = new Map<string, string>();
	const perAccount = new Map<string, Map<string, string>>();
	for (const [accountId, mailboxes] of byAccount) {
		const own = new Map<string, string>();
		for (const mailbox of mailboxes) {
			paths.set(mailbox.mailboxId, mailbox.fullPath);
			owners.set(mailbox.mailboxId, accountId);
			own.set(mailbox.mailboxId, mailbox.fullPath);
		}
		perAccount.set(accountId, own);
	}
	return {
		pathOf: (mailboxId) => paths.get(mailboxId),
		accountOf: (mailboxId) => owners.get(mailboxId),
		pathsOfAccount: (accountId) => perAccount.get(accountId) ?? new Map(),
	};
};

/**
 * A role's folder, by path. The live mailbox first; the path recorded when the
 * appointment was made when the mailbox is gone, so a folder another client
 * deleted still travels as the user's decision rather than vanishing.
 */
const folderRolesOf = (
	settings: AccountSettingsView,
	paths: ReadonlyMap<string, string>,
): ConfigAccount["folderRoles"] => {
	const roles: ConfigAccount["folderRoles"] = [];
	for (const [role, appointment] of settings.roles) {
		const folderPath =
			paths.get(appointment.mailboxId) ?? appointment.lastKnownPath;
		if (folderPath === undefined || folderPath === "") continue;
		roles.push({ role, folderPath });
	}
	return roles;
};

const folderOverridesOf = (
	accountId: string,
	index: MailboxIndex,
	byMailbox: ReadonlyMap<string, MailboxSettingsView>,
): ConfigAccount["folderOverrides"] => {
	const overrides: ConfigAccount["folderOverrides"] = [];
	for (const [mailboxId, override] of byMailbox) {
		if (index.accountOf(mailboxId) !== accountId) continue;
		const folderPath = index.pathOf(mailboxId);
		if (folderPath === undefined) continue;
		overrides.push({
			folderPath,
			displayName: override.displayName,
			muted: override.muted,
		});
	}
	return overrides;
};

/**
 * The pinned folders this account holds. The setting is one list for the whole
 * configuration while the document spells the list per account, so each path is
 * resolved against the account's own folders — the same rule every other folder
 * reference here follows, and the only one that cannot put a path on an account
 * that has no such folder.
 */
const pinnedFoldersOf = (
	pinned: readonly string[],
	paths: ReadonlyMap<string, string>,
): ConfigAccount["pinnedFolders"] => {
	const held = new Set(paths.values());
	return pinned.filter((folderPath) => held.has(folderPath));
};

const toConfigAccount = (
	account: AccountItem,
	settings: AccountSettingsView,
	pinned: readonly string[],
	index: MailboxIndex,
	byMailbox: ReadonlyMap<string, MailboxSettingsView>,
): ConfigAccount => ({
	// Field by field, never a spread of the stored row: the credential fields
	// are absent because nothing here names them, which is a guarantee that
	// survives a new column arriving on the entity.
	accountId: account.accountId,
	email: account.email,
	username: account.username,
	authType: account.authType,
	credentials: credentialsFor(account),
	isActive: account.isActive,
	imap: {
		host: account.imapHost,
		port: account.imapPort,
		tls: account.imapTls,
		startTls: account.imapStartTls,
	},
	smtp: {
		enabled: account.smtpEnabled,
		host: account.smtpHost,
		port: account.smtpPort,
		tls: account.smtpTls,
		startTls: account.smtpStartTls,
		username: account.smtpUsername,
	},
	displayName: settings.displayName,
	muted: settings.muted,
	composeLanguages: settings.composeLanguages,
	signature: {
		plainText: settings.signaturePlainText,
		html: settings.signatureHtml,
	},
	folderRoles: folderRolesOf(settings, index.pathsOfAccount(account.accountId)),
	folderOverrides: folderOverridesOf(account.accountId, index, byMailbox),
	pinnedFolders: pinnedFoldersOf(
		pinned,
		index.pathsOfAccount(account.accountId),
	),
});

const toConfigLabel = (label: LabelItem): ConfigLabel => ({
	name: label.name,
	color: label.color,
});

const toConfigFilter = (
	filter: FilterItem,
	anchor: FilterAnchorItem | undefined,
	labelNames: ReadonlyMap<string, string>,
	index: MailboxIndex,
): ConfigFilter => {
	const actionAccountId =
		filter.actionMailboxId === NO_ACTION
			? undefined
			: index.accountOf(filter.actionMailboxId);
	const actionPath =
		filter.actionMailboxId === NO_ACTION
			? undefined
			: index.pathOf(filter.actionMailboxId);
	return {
		name: filter.name,
		scope: filter.scope,
		expiresAt: filter.expiresAt ?? null,
		matchOperator: filter.matchOperator,
		literalClauses: filter.literalClauses.map((clause) => ({
			field: clause.field,
			value: clause.value,
		})),
		actionLabelName:
			filter.actionLabelId === NO_ACTION
				? null
				: (labelNames.get(filter.actionLabelId) ?? null),
		actionFolder:
			actionAccountId === undefined || actionPath === undefined
				? null
				: { accountId: actionAccountId, folderPath: actionPath },
		// The stored vector is a function of the model that produced it, so it
		// means nothing on an instance running another one. The source text is
		// what travels; import re-embeds from it.
		anchor: anchor
			? {
					sourceText: anchor.anchorSourceText,
					embeddingId: anchor.anchorEmbeddingId,
					sourceMessageId: anchor.anchorMessageId,
				}
			: null,
	};
};

/**
 * The flags a user set, named one at a time. `wellknown` and `junkOnly` have no
 * line here and so cannot be carried whatever the stored row holds — the same
 * structural guarantee the account's credential fields get.
 */
const userFlagsOf = (flags: AddressFlags | undefined): ConfigAddressFlags => {
	const stored = flags ?? {};
	const user: ConfigAddressFlags = {};
	if (stored.trusted) user.trusted = stored.trusted;
	if (stored.blocked) user.blocked = stored.blocked;
	if (stored.muted) user.muted = stored.muted;
	if (stored.vip) user.vip = stored.vip;
	if (stored.category) user.category = stored.category;
	if (stored.autoArchive) user.autoArchive = stored.autoArchive;
	if (stored.unsubscribed) user.unsubscribed = stored.unsubscribed;
	return user;
};

/**
 * An address exports exactly when the user decided something about it. A row
 * carrying only `wellknown` or `junkOnly` was decided by the machine, and a row
 * carrying nothing was merely harvested from an envelope; both come back on
 * their own once mail resyncs.
 */
export const carriesUserFlag = (flags: AddressFlags | undefined): boolean =>
	Object.keys(userFlagsOf(flags)).length > 0;

const toConfigAddressFlags = (
	address: AddressItem,
): ConfigAddressFlagsEntry => ({
	normalizedEmail: address.normalizedEmail,
	displayName: address.displayName ?? "",
	flags: userFlagsOf(address.flags),
});

const readAddresses = async (
	repositories: ConfigExportRepositories,
	accountConfigId: string,
): Promise<AddressItem[]> => {
	const addresses: AddressItem[] = [];
	let cursor: string | undefined;
	do {
		const page = await repositories.address.listByAccountConfig({
			accountConfigId,
			cursor,
		});
		addresses.push(...page.items);
		cursor = page.continuationToken;
	} while (cursor);
	return addresses;
};

const accountSettingsOf = (
	settings: SettingsView,
	accountId: string,
): AccountSettingsView =>
	settings.byAccount.get(accountId) ?? emptyAccountSettings();

/**
 * Read one configuration out as a v1 document: every decision its owner made,
 * no credential, and no fact IMAP will hand back on the next resync.
 *
 * The result is parsed by the format's own schema before it is returned, so a
 * reader that has drifted from the format fails here — while there is still a
 * database to read again — rather than on the import that needed the file.
 */
export const readConfigForExport = async (
	repositories: ConfigExportRepositories,
	accountConfigId: string,
	identity: ConfigExportIdentity,
): Promise<ReaderConfigDocument> => {
	const [accountConfig, accounts, settingRows, labels, filters, anchors] =
		await Promise.all([
			// A configuration nobody has added an account to yet holds no row. That
			// is an empty export, not a failure: the file is the migration safety
			// net, and refusing to write one is the outcome it exists to prevent.
			repositories.accountConfig
				.get(accountConfigId)
				.catch((error: unknown) => {
					if (error instanceof NotFoundError) return undefined;
					throw error;
				}),
			repositories.account.listAllByAccountConfig(accountConfigId),
			repositories.accountSetting.listByAccountConfig(accountConfigId),
			repositories.label.listByAccountConfig(accountConfigId),
			repositories.filter.listByAccountConfig(accountConfigId),
			repositories.filterAnchor.listByAccountConfig(accountConfigId),
		]);

	const liveAccounts = accounts.filter(
		(account) => account.deletedAt === undefined,
	);
	const mailboxesByAccount = new Map<string, MailboxItem[]>(
		await Promise.all(
			liveAccounts.map(
				async (account): Promise<[string, MailboxItem[]]> => [
					account.accountId,
					await repositories.mailbox.listAllByAccount(account.accountId),
				],
			),
		),
	);

	const settings = readSettings(settingRows);
	const index = buildMailboxIndex(mailboxesByAccount);
	const labelNames = new Map(
		labels.map((label) => [label.labelId, label.name] as const),
	);
	const anchorsByFilter = new Map(
		anchors.map((anchor) => [anchor.filterId, anchor] as const),
	);
	const addresses = await readAddresses(repositories, accountConfigId);

	const document: ReaderConfigDocument = {
		kind: CONFIG_KIND,
		schemaVersion: CURRENT_SCHEMA_VERSION,
		generator: {
			app: identity.app,
			version: identity.version,
			exportedAt: identity.exportedAt,
		},
		provenance: {
			accountConfigId,
			instance: identity.instance,
		},
		accountConfig: {
			name: accountConfig?.name ?? "",
			...(settings.defaultComposerFormat === undefined
				? {}
				: { defaultComposerFormat: settings.defaultComposerFormat }),
		},
		accounts: liveAccounts.map((account) =>
			toConfigAccount(
				account,
				accountSettingsOf(settings, account.accountId),
				settings.pinnedFolders,
				index,
				settings.byMailbox,
			),
		),
		labels: labels.map(toConfigLabel),
		filters: filters.map((filter) =>
			toConfigFilter(
				filter,
				anchorsByFilter.get(filter.filterId),
				labelNames,
				index,
			),
		),
		addressFlags: addresses
			.filter((address) => carriesUserFlag(address.flags))
			.map(toConfigAddressFlags),
	};

	return ReaderConfigDocumentSchema.parse(document);
};
